movie_title = "Avengers Endgame"  
two_d_or_3d = "3D"                   
ticket_price = 18.00              
number_of_tickets = 3             
is_weekend = True                 
has_student_discount = False        
popcorn_combo = "Large"            
TOTAL_PRICE = 54.00              
customer_age = 25                
member_id = "M1234"